name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        host: ${{secrets.SSH_HOST}}
        ssh-private-key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}

      script: |
      mkdir htdocs
      cd htdocs
      git clone https://github.com/unseffo/cicd-test.git
      echo "Deployment succsess!"

    
