name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decrypt SSH key
      run: echo "${{ secrets.SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa

    - name: Set permissions for SSH key
      run: chmod 600 ~/.ssh/id_rsa

    - name: Deploy code
      run: |
        scp -r * ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/nosleepcoders
