name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        host: ${{secrets.SSH_HOST}}
        ssh-private-key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}

    - name: Clone repository to server
      run: ssh ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} 'git clone https://github.com/unseffo/cicd-test.git /home/nosleepcoders/htdocs'
