name: Deploy

on:
  push:
    branches:
      - main  # змініть це на назву вашої основної гілки

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy code
      run: |
        scp -r * ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/nosleepcoders
